/*
 * This source file was generated by the Gradle 'init' task
 */
package demo;

import demo.io.http.HttpServer;
import demo.io.socket.SocketServer;
import demo.log.Log;
import demo.util.id.GenerateId;
import demo.util.id.GenerateIdRedis;

public class DemoServer {
    private static final String TAG = "DemoServer";
    public static GenerateId genUserId = new GenerateIdRedis();

    public static void main(String[] args) throws Exception {
        Log.info(TAG, "main");
        Runtime.getRuntime().addShutdownHook(new Thread(DemoServer::onShutdown));
        init();
    }

    private static void init() {
        Log.info(TAG, "starting");
        try {
            HttpServer.start(96);
            SocketServer.start(3096);
            Log.info(TAG, "started");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private static void onShutdown() {
        Log.info(TAG, "stopping");
        try {

            Log.info(TAG, "stopped");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
